# .github/workflows/pypi-on-release.yaml
# ref: https://www.seanh.cc/2022/05/21/publishing-python-packages-from-github-actions/#the-publish-workflow
name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
